services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reloading during development
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
